# Generated by Django 5.0.4 on 2024-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('email', models.TextField()),
                ('contact_number', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
